Result:  Exception: (fun b -> b)
